### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/ARTEMIS#1]
Error in writeOutputs in the readme
currently it's, but should be
writeOutputs(output_all, processedAll = processedAll, processedEras = processedEras,
connectionDetails = connectionDetails, cdmSchema = cdmSchema,
regGroups = regGroups, regStats = regStats, stringDF = stringDF,
con_df = con_df)

writeOutputs(output_all, output_processed= processedAll, processedEras = processedEras,
connectionDetails = connectionDetails, cdmSchema = cdmSchema,
regGroups = regGroups, regStats = regStats, stringDF = stringDF,
con_df = con_df)

also in the end when it says "submit an issue", it redirects to the old github

**Comment by laurencelawrencearcher** [comment]
Updated writeOutputs function with correct variable name, and updated readme to direct to the correct issues page

Thank you
